---
title: "Análisis de Correspondencia Simple y Múltiple"
author: "Pamela E. Pairo"
lang: es
format:
  html:
    theme:  flatly
    code-fold: show
    code-tools: true
    toc: true
    toc-location: left
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(tidyverse)
library(factoextra)
library(FactoMineR)
```

```{r}

data(housetasks)
housetasks

```

```{r}
summary(housetasks)
```

# Análisis de Correspondencia Simple
## Test de Independencia

```{r}
chisq.test(housetasks)
```
## Análisis de perfiles
### Perfil Fila

```{r}
# Perfiles fila (la suma de las frecuencias de cada fila da 1)
pf_ht <-  round(prop.table(as.matrix(housetasks),1),3)
pf_ht
```
```{r}
df_pf_ht <- as.data.frame(pf_ht) 
df_pf_ht$tareas <- rownames(pf_ht)
df_pf_ht <- df_pf_ht %>% pivot_longer(!tareas, names_to = "Variable", values_to = "valor")

ggplot(data=df_pf_ht, aes(y = valor, x= tareas, color=Variable))+geom_line(aes(group = Variable))+
  labs(title = 'Distribución del responsable de las tareas del hogar según tareas',
              y = 'Frecuencia', x = 'Tareas') +
  scale_color_viridis_d(name='responsable tareas del hogar')+theme(axis.text.x = element_text(angle = 45, hjust = 1))
```



### Perfil Columna

# Análisis de Correspondencia Múltiple

